label var crime                    "crimes committed per capita"
label var nox                      "nitrous oxide, parts per 100m"
label var rooms                    "avg number of rooms per house"
label var dist                     "weighted dist. to 5 employ centers"
label var radial                   "accessibiliy index to radial hghwys"
label var proptax                  "property tax per $1000"
label var stratio                  "average student--teacher ratio"
label var lowstat                  "% of people 'lower status'"
label var lprice                   "log(price)"
label var lnox                     "log(nox)"
label var lproptax                 "log(proptax)"
label var ldist "log(dist)"
label data "Housing price data for Boston-area communities"
